# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

defaultCluster: Optional[str]
"""
Default cluster, if provided will be used when no cluster is provided
"""

host: Optional[str]
"""
Clickhouse server url
"""

password: Optional[str]
"""
Clickhouse user password with admin privileges
"""

port: Optional[int]
"""
Clickhouse server native protocol port (TCP)
"""

secure: Optional[bool]
"""
Clickhouse secure connection
"""

username: Optional[str]
"""
Clickhouse username with admin privileges
"""

