# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('clickhouse')


class _ExportableConfig(types.ModuleType):
    @property
    def default_cluster(self) -> Optional[str]:
        """
        Default cluster, if provided will be used when no cluster is provided
        """
        return __config__.get('defaultCluster')

    @property
    def host(self) -> Optional[str]:
        """
        Clickhouse server url
        """
        return __config__.get('host')

    @property
    def password(self) -> Optional[str]:
        """
        Clickhouse user password with admin privileges
        """
        return __config__.get('password')

    @property
    def port(self) -> Optional[int]:
        """
        Clickhouse server native protocol port (TCP)
        """
        return __config__.get_int('port')

    @property
    def secure(self) -> Optional[bool]:
        """
        Clickhouse secure connection
        """
        return __config__.get_bool('secure')

    @property
    def username(self) -> Optional[str]:
        """
        Clickhouse username with admin privileges
        """
        return __config__.get('username')

