// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhouse
{
    public static class GetDbs
    {
        /// <summary>
        /// Datasource to retrieve all databases set in clickhouse instance
        /// </summary>
        public static Task<GetDbsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDbsResult>("clickhouse:index/getDbs:getDbs", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Datasource to retrieve all databases set in clickhouse instance
        /// </summary>
        public static Output<GetDbsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDbsResult>("clickhouse:index/getDbs:getDbs", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetDbsResult
    {
        public readonly ImmutableArray<Outputs.GetDbsDbResult> Dbs;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetDbsResult(
            ImmutableArray<Outputs.GetDbsDbResult> dbs,

            string id)
        {
            Dbs = dbs;
            Id = id;
        }
    }
}
