// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/Triple-Whale/pulumi-clickhouse/sdk/go/clickhouse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Default cluster, if provided will be used when no cluster is provided
func GetDefaultCluster(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhouse:defaultCluster")
}

// Clickhouse server url
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhouse:host")
}

// Clickhouse user password with admin privileges
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhouse:password")
}

// Clickhouse server native protocol port (TCP)
func GetPort(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "clickhouse:port")
}

// Clickhouse secure connection
func GetSecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "clickhouse:secure")
}

// Clickhouse username with admin privileges
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhouse:username")
}
