// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhouse.Outputs
{

    [OutputType]
    public sealed class GetDbsDbResult
    {
        public readonly string Comment;
        public readonly string DataPath;
        public readonly string Engine;
        public readonly string MetadataPath;
        public readonly string Name;
        public readonly string Uuid;

        [OutputConstructor]
        private GetDbsDbResult(
            string comment,

            string dataPath,

            string engine,

            string metadataPath,

            string name,

            string uuid)
        {
            Comment = comment;
            DataPath = dataPath;
            Engine = engine;
            MetadataPath = metadataPath;
            Name = name;
            Uuid = uuid;
        }
    }
}
