// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhouse.Outputs
{

    [OutputType]
    public sealed class TableColumn
    {
        /// <summary>
        /// Database comment, it will be codified in a json along with come metadata information (like cluster name in case of clustering)
        /// </summary>
        public readonly string? Comment;
        public readonly string? Defaultexpression;
        public readonly string? Defaultkind;
        /// <summary>
        /// Column Name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Column Type
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private TableColumn(
            string? comment,

            string? defaultexpression,

            string? defaultkind,

            string name,

            string type)
        {
            Comment = comment;
            Defaultexpression = defaultexpression;
            Defaultkind = defaultkind;
            Name = name;
            Type = type;
        }
    }
}
