// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhouse.Outputs
{

    [OutputType]
    public sealed class TableIndex
    {
        public readonly string Expression;
        public readonly int? Granularity;
        /// <summary>
        /// Column Name
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Column Type
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private TableIndex(
            string expression,

            int? granularity,

            string name,

            string type)
        {
            Expression = expression;
            Granularity = granularity;
            Name = name;
            Type = type;
        }
    }
}
