# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .db import *
from .get_dbs import *
from .provider import *
from .role import *
from .table import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_clickhouse.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_clickhouse.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "clickhouse",
  "mod": "index/db",
  "fqn": "pulumi_clickhouse",
  "classes": {
   "clickhouse:index/db:Db": "Db"
  }
 },
 {
  "pkg": "clickhouse",
  "mod": "index/role",
  "fqn": "pulumi_clickhouse",
  "classes": {
   "clickhouse:index/role:Role": "Role"
  }
 },
 {
  "pkg": "clickhouse",
  "mod": "index/table",
  "fqn": "pulumi_clickhouse",
  "classes": {
   "clickhouse:index/table:Table": "Table"
  }
 },
 {
  "pkg": "clickhouse",
  "mod": "index/user",
  "fqn": "pulumi_clickhouse",
  "classes": {
   "clickhouse:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "clickhouse",
  "token": "pulumi:providers:clickhouse",
  "fqn": "pulumi_clickhouse",
  "class": "Provider"
 }
]
"""
)
