# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'TableColumnArgs',
    'TablePartitionByArgs',
]

@pulumi.input_type
class TableColumnArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 type: pulumi.Input[str]):
        """
        :param pulumi.Input[str] name: Column Name
        :param pulumi.Input[str] type: Column Type
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        Column Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        """
        Column Type
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)


@pulumi.input_type
class TablePartitionByArgs:
    def __init__(__self__, *,
                 by: pulumi.Input[str],
                 partition_function: Optional[pulumi.Input[str]] = None):
        """
        :param pulumi.Input[str] by: Column to use as part of the partition key
        :param pulumi.Input[str] partition_function: Partition function, could be empty or one of following: toYYYYMM, toYYYYMMDD or toYYYYMMDDhhmmss
        """
        pulumi.set(__self__, "by", by)
        if partition_function is not None:
            pulumi.set(__self__, "partition_function", partition_function)

    @property
    @pulumi.getter
    def by(self) -> pulumi.Input[str]:
        """
        Column to use as part of the partition key
        """
        return pulumi.get(self, "by")

    @by.setter
    def by(self, value: pulumi.Input[str]):
        pulumi.set(self, "by", value)

    @property
    @pulumi.getter(name="partitionFunction")
    def partition_function(self) -> Optional[pulumi.Input[str]]:
        """
        Partition function, could be empty or one of following: toYYYYMM, toYYYYMMDD or toYYYYMMDDhhmmss
        """
        return pulumi.get(self, "partition_function")

    @partition_function.setter
    def partition_function(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "partition_function", value)


