# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'TableColumnArgs',
    'TableIndexArgs',
    'TablePartitionByArgs',
]

@pulumi.input_type
class TableColumnArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 type: pulumi.Input[str],
                 array: Optional[pulumi.Input[bool]] = None,
                 comment: Optional[pulumi.Input[str]] = None,
                 nullable: Optional[pulumi.Input[bool]] = None):
        """
        :param pulumi.Input[str] name: Column Name
        :param pulumi.Input[str] type: Column Type
        :param pulumi.Input[str] comment: Database comment, it will be codified in a json along with come metadata information (like cluster name in case of clustering)
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)
        if array is not None:
            pulumi.set(__self__, "array", array)
        if comment is not None:
            pulumi.set(__self__, "comment", comment)
        if nullable is not None:
            pulumi.set(__self__, "nullable", nullable)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        Column Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        """
        Column Type
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def array(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "array")

    @array.setter
    def array(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "array", value)

    @property
    @pulumi.getter
    def comment(self) -> Optional[pulumi.Input[str]]:
        """
        Database comment, it will be codified in a json along with come metadata information (like cluster name in case of clustering)
        """
        return pulumi.get(self, "comment")

    @comment.setter
    def comment(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "comment", value)

    @property
    @pulumi.getter
    def nullable(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "nullable")

    @nullable.setter
    def nullable(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "nullable", value)


@pulumi.input_type
class TableIndexArgs:
    def __init__(__self__, *,
                 expression: pulumi.Input[str],
                 name: pulumi.Input[str],
                 type: pulumi.Input[str],
                 granularity: Optional[pulumi.Input[int]] = None):
        """
        :param pulumi.Input[str] name: Column Name
        :param pulumi.Input[str] type: Column Type
        """
        pulumi.set(__self__, "expression", expression)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)
        if granularity is not None:
            pulumi.set(__self__, "granularity", granularity)

    @property
    @pulumi.getter
    def expression(self) -> pulumi.Input[str]:
        return pulumi.get(self, "expression")

    @expression.setter
    def expression(self, value: pulumi.Input[str]):
        pulumi.set(self, "expression", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        Column Name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        """
        Column Type
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def granularity(self) -> Optional[pulumi.Input[int]]:
        return pulumi.get(self, "granularity")

    @granularity.setter
    def granularity(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "granularity", value)


@pulumi.input_type
class TablePartitionByArgs:
    def __init__(__self__, *,
                 by: pulumi.Input[str],
                 partition_function: Optional[pulumi.Input[str]] = None):
        """
        :param pulumi.Input[str] by: Column to use as part of the partition key
        :param pulumi.Input[str] partition_function: Partition function, could be empty or one of following: toYYYYMM, toYYYYMMDD or toYYYYMMDDhhmmss
        """
        pulumi.set(__self__, "by", by)
        if partition_function is not None:
            pulumi.set(__self__, "partition_function", partition_function)

    @property
    @pulumi.getter
    def by(self) -> pulumi.Input[str]:
        """
        Column to use as part of the partition key
        """
        return pulumi.get(self, "by")

    @by.setter
    def by(self, value: pulumi.Input[str]):
        pulumi.set(self, "by", value)

    @property
    @pulumi.getter(name="partitionFunction")
    def partition_function(self) -> Optional[pulumi.Input[str]]:
        """
        Partition function, could be empty or one of following: toYYYYMM, toYYYYMMDD or toYYYYMMDDhhmmss
        """
        return pulumi.get(self, "partition_function")

    @partition_function.setter
    def partition_function(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "partition_function", value)


