# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'TableColumn',
    'TableIndex',
    'TablePartitionBy',
    'GetDbsDbResult',
]

@pulumi.output_type
class TableColumn(dict):
    def __init__(__self__, *,
                 name: str,
                 type: str,
                 array: Optional[bool] = None,
                 comment: Optional[str] = None,
                 nullable: Optional[bool] = None):
        """
        :param str name: Column Name
        :param str type: Column Type
        :param str comment: Database comment, it will be codified in a json along with come metadata information (like cluster name in case of clustering)
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)
        if array is not None:
            pulumi.set(__self__, "array", array)
        if comment is not None:
            pulumi.set(__self__, "comment", comment)
        if nullable is not None:
            pulumi.set(__self__, "nullable", nullable)

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        Column Name
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def type(self) -> str:
        """
        Column Type
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def array(self) -> Optional[bool]:
        return pulumi.get(self, "array")

    @property
    @pulumi.getter
    def comment(self) -> Optional[str]:
        """
        Database comment, it will be codified in a json along with come metadata information (like cluster name in case of clustering)
        """
        return pulumi.get(self, "comment")

    @property
    @pulumi.getter
    def nullable(self) -> Optional[bool]:
        return pulumi.get(self, "nullable")


@pulumi.output_type
class TableIndex(dict):
    def __init__(__self__, *,
                 expression: str,
                 name: str,
                 type: str,
                 granularity: Optional[int] = None):
        """
        :param str name: Column Name
        :param str type: Column Type
        """
        pulumi.set(__self__, "expression", expression)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)
        if granularity is not None:
            pulumi.set(__self__, "granularity", granularity)

    @property
    @pulumi.getter
    def expression(self) -> str:
        return pulumi.get(self, "expression")

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        Column Name
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def type(self) -> str:
        """
        Column Type
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def granularity(self) -> Optional[int]:
        return pulumi.get(self, "granularity")


@pulumi.output_type
class TablePartitionBy(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "partitionFunction":
            suggest = "partition_function"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in TablePartitionBy. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        TablePartitionBy.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        TablePartitionBy.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 by: str,
                 partition_function: Optional[str] = None):
        """
        :param str by: Column to use as part of the partition key
        :param str partition_function: Partition function, could be empty or one of following: toYYYYMM, toYYYYMMDD or toYYYYMMDDhhmmss
        """
        pulumi.set(__self__, "by", by)
        if partition_function is not None:
            pulumi.set(__self__, "partition_function", partition_function)

    @property
    @pulumi.getter
    def by(self) -> str:
        """
        Column to use as part of the partition key
        """
        return pulumi.get(self, "by")

    @property
    @pulumi.getter(name="partitionFunction")
    def partition_function(self) -> Optional[str]:
        """
        Partition function, could be empty or one of following: toYYYYMM, toYYYYMMDD or toYYYYMMDDhhmmss
        """
        return pulumi.get(self, "partition_function")


@pulumi.output_type
class GetDbsDbResult(dict):
    def __init__(__self__, *,
                 comment: str,
                 data_path: str,
                 engine: str,
                 metadata_path: str,
                 name: str,
                 uuid: str):
        pulumi.set(__self__, "comment", comment)
        pulumi.set(__self__, "data_path", data_path)
        pulumi.set(__self__, "engine", engine)
        pulumi.set(__self__, "metadata_path", metadata_path)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "uuid", uuid)

    @property
    @pulumi.getter
    def comment(self) -> str:
        return pulumi.get(self, "comment")

    @property
    @pulumi.getter(name="dataPath")
    def data_path(self) -> str:
        return pulumi.get(self, "data_path")

    @property
    @pulumi.getter
    def engine(self) -> str:
        return pulumi.get(self, "engine")

    @property
    @pulumi.getter(name="metadataPath")
    def metadata_path(self) -> str:
        return pulumi.get(self, "metadata_path")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def uuid(self) -> str:
        return pulumi.get(self, "uuid")


