// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./input";
import * as outputs from "./output";

export interface TableColumn {
    comment?: pulumi.Input<string>;
    defaultExpression?: pulumi.Input<string>;
    defaultKind?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface TableIndex {
    expression: pulumi.Input<string>;
    granularity?: pulumi.Input<number>;
    name: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface TablePartitionBy {
    by: pulumi.Input<string>;
    mod?: pulumi.Input<string>;
    partitionFunction?: pulumi.Input<string>;
}

export interface ViewColumn {
    comment?: pulumi.Input<string>;
    defaultExpression?: pulumi.Input<string>;
    defaultKind?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    type: pulumi.Input<string>;
}
