// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetDbsDb {
    comment: string;
    dataPath: string;
    engine: string;
    metadataPath: string;
    name: string;
    uuid: string;
}

export interface TableColumn {
    /**
     * Database comment, it will be codified in a json along with come metadata information (like cluster name in case of clustering)
     */
    comment: string;
    defaultExpression: string;
    defaultKind: string;
    /**
     * Column Name
     */
    name: string;
    /**
     * Column Type
     */
    type: string;
}

export interface TableIndex {
    expression: string;
    granularity?: number;
    /**
     * Column Name
     */
    name: string;
    /**
     * Column Type
     */
    type: string;
}

export interface TablePartitionBy {
    /**
     * Column to use as part of the partition key
     */
    by: string;
    mod?: string;
    /**
     * Partition function, could be empty or one of following: toYYYYMM, toYYYYMMDD or toYYYYMMDDhhmmss
     */
    partitionFunction?: string;
}

