// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./input";
import * as outputs from "./output";

export interface GetDbsDb {
    comment: string;
    dataPath: string;
    engine: string;
    metadataPath: string;
    name: string;
    uuid: string;
}

export interface TableColumn {
    comment?: string;
    defaultExpression?: string;
    defaultKind?: string;
    name: string;
    type: string;
}

export interface TableIndex {
    expression: string;
    granularity?: number;
    name: string;
    type: string;
}

export interface TablePartitionBy {
    by: string;
    mod?: string;
    partitionFunction?: string;
}

export interface ViewColumn {
    comment?: string;
    defaultExpression?: string;
    defaultKind?: string;
    name: string;
    type: string;
}

