// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clickhouse

import (
	"context"
	"reflect"

	"github.com/Triple-Whale/pulumi-clickhouse/sdk/go/clickhouse/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Datasource to retrieve all databases set in clickhouse instance
func GetDbs(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetDbsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDbsResult
	err := ctx.Invoke("clickhouse:index/getDbs:getDbs", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDbs.
type GetDbsResult struct {
	Dbs []GetDbsDb `pulumi:"dbs"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetDbsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetDbsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetDbsResult, error) {
		r, err := GetDbs(ctx, opts...)
		var s GetDbsResult
		if r != nil {
			s = *r
		}
		return s, err
	}).(GetDbsResultOutput)
}

// A collection of values returned by getDbs.
type GetDbsResultOutput struct{ *pulumi.OutputState }

func (GetDbsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDbsResult)(nil)).Elem()
}

func (o GetDbsResultOutput) ToGetDbsResultOutput() GetDbsResultOutput {
	return o
}

func (o GetDbsResultOutput) ToGetDbsResultOutputWithContext(ctx context.Context) GetDbsResultOutput {
	return o
}

func (o GetDbsResultOutput) Dbs() GetDbsDbArrayOutput {
	return o.ApplyT(func(v GetDbsResult) []GetDbsDb { return v.Dbs }).(GetDbsDbArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDbsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDbsResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDbsResultOutput{})
}
