// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Datasource to retrieve all databases set in clickhouse instance
 */
export function getDbs(opts?: pulumi.InvokeOptions): Promise<GetDbsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("clickhouse:index/getDbs:getDbs", {
    }, opts);
}

/**
 * A collection of values returned by getDbs.
 */
export interface GetDbsResult {
    readonly dbs: outputs.GetDbsDb[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
/**
 * Datasource to retrieve all databases set in clickhouse instance
 */
export function getDbsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetDbsResult> {
    return pulumi.output(getDbs(opts))
}
