// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the clickhouse package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'clickhouse';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Default cluster, if provided will be used when no cluster is provided
     */
    public readonly defaultCluster!: pulumi.Output<string | undefined>;
    /**
     * Clickhouse server url
     */
    public readonly host!: pulumi.Output<string>;
    /**
     * Clickhouse user password with admin privileges
     */
    public readonly password!: pulumi.Output<string | undefined>;
    /**
     * Clickhouse username with admin privileges
     */
    public readonly username!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.host === undefined) && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            if ((!args || args.port === undefined) && !opts.urn) {
                throw new Error("Missing required property 'port'");
            }
            resourceInputs["defaultCluster"] = args ? args.defaultCluster : undefined;
            resourceInputs["host"] = args?.host ? pulumi.secret(args.host) : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["port"] = pulumi.output(args ? args.port : undefined).apply(JSON.stringify);
            resourceInputs["secure"] = pulumi.output(args ? args.secure : undefined).apply(JSON.stringify);
            resourceInputs["username"] = args ? args.username : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["host", "password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Default cluster, if provided will be used when no cluster is provided
     */
    defaultCluster?: pulumi.Input<string>;
    /**
     * Clickhouse server url
     */
    host: pulumi.Input<string>;
    /**
     * Clickhouse user password with admin privileges
     */
    password?: pulumi.Input<string>;
    /**
     * Clickhouse server native protocol port (TCP)
     */
    port: pulumi.Input<number>;
    /**
     * Clickhouse secure connection
     */
    secure?: pulumi.Input<boolean>;
    /**
     * Clickhouse username with admin privileges
     */
    username?: pulumi.Input<string>;
}
